services:
  store-ms:
    build: .
    ports:
      - "3005:3005"
    env_file: ".env"
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /usr/app
          ignore:
            - node_modules/
            - built/
            - README.md
            - .gitignore

    