-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Tienda"
(
    tienda_id serial NOT NULL,
    uid character varying(100) NOT NULL,
    nombre character varying(100),
    fecha_suscripcion date NOT NULL,
    direccion character varying(200),
    descripcion text,
    fotos character varying(16),
    enlace character varying(200),
    PRIMARY KEY (tienda_id)
);

CREATE TABLE IF NOT EXISTS public."Productos"
(
    producto_id serial NOT NULL,
    tienda_id serial,
    lognitud character varying(100),
    referencia character varying(100) NOT NULL,
    nombre character varying(100),
    descripcion character varying(100),
    foto character varying(100),
    PRIMARY KEY (producto_id)
);

CREATE TABLE IF NOT EXISTS public."Tags"
(
    id_tag serial NOT NULL,
    descripcion text,
    nombre character varying(100),
    tipo character varying(100),
    PRIMARY KEY (id_tag)
);

CREATE TABLE IF NOT EXISTS public."Clasificacion"
(
    id_producto serial NOT NULL,
    id_tag serial NOT NULL,
    id_tienda serial NOT NULL
);

ALTER TABLE IF EXISTS public."Productos"
    ADD CONSTRAINT tienda FOREIGN KEY (tienda_id)
    REFERENCES public."Tienda" (tienda_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public."Clasificacion"
    ADD CONSTRAINT producto FOREIGN KEY (id_producto)
    REFERENCES public."Productos" (producto_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Clasificacion"
    ADD CONSTRAINT tag FOREIGN KEY (id_tag)
    REFERENCES public."Tags" (id_tag) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Clasificacion"
    ADD CONSTRAINT tienda FOREIGN KEY (id_tienda)
    REFERENCES public."Tienda" (tienda_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;